#! /usr/bin/bash

# Runs money.py from a virtual environment in the same directory named "env"
# This will not work with sh because of BASH_SOURCE.
# If I can find another solution to BASH_SOURCE that works with sh, I can rewrite the script.

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

C=''
for i in "$@"; do 
    i="${i//\\/\\\\}"
    C="$C \"${i//\"/\\\"}\""
done

bash -c "$parent_path/env/bin/python $parent_path/money.py $C"
